server:
  port: ${PORT:8081}

spring:
  mobile:
    devicedelegatingviewresolver:
      enabled: true
      enable-fallback: true
      mobile-prefix: /mobile/
      # mobile-suffix: .mob
      normal-prefix: /
      # normal-suffix: .nor
      tablet-prefix: /tablet/
      # tablet-suffix: .tab